//
//  CommonDefine.h
//  AtomicArtist
//
//  Created by Chen XiaoLiang on 12-5-17.
//  Copyright (c) 2012年 seraphCXL. All rights reserved.
//

#ifndef AtomicArtist_CommonDefine_h
#define AtomicArtist_CommonDefine_h

#pragma mark Thumbnail
#define TITLELABEL_FONT_SIZE_IPHONE ((int)14)
#define TITLELABEL_FONT_SIZE_IPAD ((int)16)

#define THUMBNAIL_SIZE_IPHONE ((int)96)
#define THUMBNAIL_SIZE_IPAD ((int)128)

#pragma mark DetailView
#define BAR_THUMBNAIL_SIZE ((int)75)
#define BAR_THUMBNAIL_SPACE_HEIGHT ((int)2)

#pragma mark ItemView
#define ITEMVIEW_TITLELABEL_FONT_SIZE_IPHONE TITLELABEL_FONT_SIZE_IPHONE
#define ITEMVIEW_TITLELABEL_FONT_SIZE_IPAD TITLELABEL_FONT_SIZE_IPAD

#define ITEMVIEW_SIZE_FRAME_IPHONE THUMBNAIL_SIZE_IPHONE
#define ITEMVIEW_SIZE_FRAME_IPAD THUMBNAIL_SIZE_IPAD

#define ITEMVIEW_TABLEVIEW_MARGIN_IPHONE ((int)16)
#define ITEMVIEW_TABLEVIEW_MARGIN_IPAD ((int)32)

#pragma mark GroupView
#define GROUPVIEW_TITLELABEL_SPACE ((int)4)
#define GROUPVIEW_TITLELABEL_HEIGHT ((int)28)

#define GROUPVIEW_TITLELABEL_FONT_SIZE_IPHONE TITLELABEL_FONT_SIZE_IPHONE
#define GROUPVIEW_TITLELABEL_FONT_SIZE_IPAD TITLELABEL_FONT_SIZE_IPAD

#define GROUPVIEW_SIZE_FRAME_IPHONE ITEMVIEW_SIZE_FRAME_IPHONE
#define GROUPVIEW_SIZE_POSTERIMAGE_IPHONE (GROUPVIEW_SIZE_FRAME_IPHONE - (GROUPVIEW_TITLELABEL_HEIGHT + GROUPVIEW_TITLELABEL_SPACE))

#define GROUPVIEW_SIZE_FRAME_IPAD ITEMVIEW_SIZE_FRAME_IPAD
#define GROUPVIEW_SIZE_POSTERIMAGE_IPAD (GROUPVIEW_SIZE_FRAME_IPAD - (GROUPVIEW_TITLELABEL_HEIGHT + GROUPVIEW_TITLELABEL_SPACE))

#define GROUPVIEW_TABLEVIEW_MARGIN_IPHONE ((int)16)
#define GROUPVIEW_TABLEVIEW_MARGIN_IPAD ((int)32)

#pragma mark PosterImage
#define POSTERIMAGE_SIZE_IPHONE GROUPVIEW_SIZE_FRAME_IPHONE
#define POSTERIMAGE_SIZE_IPAD GROUPVIEW_SIZE_FRAME_IPAD

#pragma mark Cache
#define CACHE_BUFFERPAGE_GROUP ((int)2)
#define CACHE_BUFFERPAGE_ITEM ((int)2)

#ifdef DEBUG
#define debug_NSLog(format, ...) NSLog(format, ## __VA_ARGS__)
#else
#define debug_NSLog(format, ...)
#endif

#endif
